version: '3.4'

services:
  api:
    image: reclamentrancoso_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80" # Mapeia a porta 80 do contêiner para a porta 5000 do host
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=reclame_trancoso;Username=dridev;Password=130722; # Lembre-se de atualizar a porta aqui

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=dridev
      - POSTGRES_PASSWORD=130722
      - POSTGRES_DB=reclame_trancoso
    ports:
      - "5433:5432"  # Mapeia a porta 5432 do contêiner para a porta 5433 do host

  ef-migrations:
    image: reclamentrancoso_api:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=reclame_trancoso;Username=dridev;Password=130722; # Atualize a porta aqui
    command: >
      sh -c "dotnet ef database update"
